openapi: 3.0.0
info:
  title: STD23059 - TD1
  description: |
    An API documentation test based on OpenAPI 3.0
  version: 1.0.0
servers:
  - url: https://localhost.std23059.com
paths:
  /customers:
    get:
      summary: Retrieve a list of customers
      responses:
        '200':
          description: A list of customers
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Customer'
components:
  schemas:
    Customer:
      type: object
      properties:
        name:
          type: string
        age:
          type: integer
          format: int32
      required:
        - name
        - age
